# Generated by Django 4.1.5 on 2023-01-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(null=True, upload_to="project/"),
        ),
    ]
