# Generated by Django 4.1.5 on 2023-01-24 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projectapp", "0002_alter_project_image"),
        ("articleapp", "0002_alter_article_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article",
                to="projectapp.project",
            ),
        ),
    ]
