# Generated by Django 4.1.5 on 2023-01-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articleapp", "0003_article_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="like",
            field=models.IntegerField(default=0),
        ),
    ]
